// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GuardarConfiguracion(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GuardarConfiguracion'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ObtenerConfiguracion() {
  return window['go']['main']['App']['ObtenerConfiguracion']();
}
