// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CambiarEstadoMotor(arg1:boolean):Promise<string>;

export function GuardarConfiguracion(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<string>;

export function ObtenerConfiguracion():Promise<Record<string, any>>;
